use GENERIC_WORKFLOW;

-- Insert testing data in G_WF_WORKFLOW table 
INSERT INTO G_WF_WORKFLOW( WF_CODE, WF_NAME, EXPIRY_IN_DAYS, EXPIRY_ACTION, CLOSE_IN_DAYS, WF_RECONFIG, BRANCH_ENABLED, VERSION, 
	CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES('SNG_ISG','ISG SERVICE REQUEST', 30, 'RETURN', 5, 'N', 'N', 1, 'SYS', sysdate(),'SYS', sysdate());

INSERT INTO G_WF_WORKFLOW( WF_CODE, WF_NAME, EXPIRY_IN_DAYS, EXPIRY_ACTION, CLOSE_IN_DAYS, WF_RECONFIG, BRANCH_ENABLED, VERSION, 
	CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES('SNG_IPG','IPG SERVICE REQUEST', 30, 'RETURN', 5, 'N', 'N', 1, 'SYS', sysdate(),'SYS', sysdate());

select * from G_WF_WORKFLOW;


-- Insert testing data in G_WF_STEP table

INSERT INTO G_WF_SUBTYPE(WF_UID, LABEL, FIELD_VALUE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES((SELECT UID from G_WF_WORKFLOW where WF_CODE = 'SNG_ISG'), 'SUBTYPE 1', 'ST1', 'SYS', sysdate(),'SYS', sysdate());

INSERT INTO G_WF_SUBTYPE(WF_UID, LABEL, FIELD_VALUE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES((SELECT UID from G_WF_WORKFLOW where WF_CODE = 'SNG_ISG'), 'SUBTYPE 2', 'ST2', 'SYS', sysdate(),'SYS', sysdate());

SELECT * FROM G_WF_SUBTYPE;

-- Insert testing data in G_WF_STEP table

INSERT INTO G_WF_STEP(CURRENT_OWNER, OWNER_GROUP, WF_UID, STEP_NAME, TIME_LIMIT_DAYS, STEP_SEQ, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES('User1', '', (SELECT UID from G_WF_WORKFLOW where WF_CODE = 'SNG_ISG'), 'STEP 1', 30, 1, 'SYS', sysdate(),'SYS', sysdate());

INSERT INTO G_WF_STEP(CURRENT_OWNER, OWNER_GROUP, WF_UID, STEP_NAME, TIME_LIMIT_DAYS, STEP_SEQ, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES('', 'GROUP 1', (SELECT UID from G_WF_WORKFLOW where WF_CODE = 'SNG_ISG'), 'STEP 2', 30, 1, 'SYS', sysdate(),'SYS', sysdate());

SELECT * FROM G_WF_STEP; 


-- Insert testing data in G_WF_FIELD table

INSERT INTO G_WF_FIELD (WF_UID, FIELD_LABEL, FIELD_TYPE, FIELD_NAME, FIELD_SEQ, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES((SELECT UID from G_WF_WORKFLOW where WF_CODE = 'SNG_ISG'), 'FIELD 1', 'TEXT', 'F1', 1, 'SYS', sysdate(),'SYS', sysdate() );

INSERT INTO G_WF_FIELD (WF_UID, FIELD_LABEL, FIELD_TYPE, FIELD_NAME, FIELD_SEQ, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES((SELECT UID from G_WF_WORKFLOW where WF_CODE = 'SNG_ISG'), 'FIELD 2', 'DROPDOWN', 'F2', 2, 'SYS', sysdate(),'SYS', sysdate() );

SELECT * FROM G_WF_FIELD;

-- Insert testing data in G_WF_FIELD table

INSERT INTO G_WF_FIELD_OPTION(FIELD_UID, LABEL, FIELD_VALUE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES((SELECT UID from G_WF_FIELD where FIELD_NAME = 'F2'), 'OPTION 1', 'OPT1', 'SYS', sysdate(),'SYS', sysdate());

INSERT INTO G_WF_FIELD_OPTION(FIELD_UID, LABEL, FIELD_VALUE, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
VALUES((SELECT UID from G_WF_FIELD where FIELD_NAME = 'F2'), 'OPTION 2', 'OPT2', 'SYS', sysdate(),'SYS', sysdate() );

SELECT * FROM G_WF_FIELD_OPTION;