DROP DATABASE IF EXISTS GENERIC_WORKFLOW;

CREATE DATABASE GENERIC_WORKFLOW;

USE GENERIC_WORKFLOW;

CREATE TABLE G_WF_WORKFLOW (
	UID INTEGER AUTO_INCREMENT NOT NULL,
    WF_CODE VARCHAR(100) NOT NULL UNIQUE,
    WF_NAME VARCHAR(100) NOT NULL,
    EXPIRY_IN_DAYS INTEGER DEFAULT 0,
    EXPIRY_ACTION VARCHAR(50),
    CLOSE_IN_DAYS INTEGER DEFAULT 0,
    WF_RECONFIG CHAR(2) DEFAULT 'N',
    BRANCH_ENABLED CHAR(2) DEFAULT 'N',
    VERSION INTEGER DEFAULT 1,
    CREATED_BY VARCHAR(100),
    CREATED_DATE DATETIME,
    UPDATED_BY VARCHAR(100),
    UPDATED_DATE DATETIME,
    DELETE_FLAG CHAR(1) DEFAULT 'N',
    PRIMARY KEY (UID)
);

CREATE TABLE G_WF_SUBTYPE (
	UID INTEGER AUTO_INCREMENT NOT NULL,
    WF_UID INTEGER NOT NULL,
    LABEL VARCHAR(100) NOT NULL,
    FIELD_VALUE VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_DATE DATETIME,
    UPDATED_BY VARCHAR(100),
    UPDATED_DATE DATETIME,
    DELETE_FLAG CHAR(1) DEFAULT 'N',
    PRIMARY KEY (UID),
    FOREIGN KEY (WF_UID) REFERENCES G_WF_WORKFLOW(UID)
);

CREATE TABLE G_WF_STEP (
	UID INTEGER AUTO_INCREMENT NOT NULL,
    CURRENT_OWNER VARCHAR(100),
    OWNER_GROUP VARCHAR(100),
    WF_UID INTEGER NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    TIME_LIMIT_DAYS INTEGER,
    STEP_SEQ INTEGER,
    CREATED_BY VARCHAR(100),
    CREATED_DATE DATETIME,
    UPDATED_BY VARCHAR(100),
    UPDATED_DATE DATETIME,
    DELETE_FLAG CHAR(1) DEFAULT 'N',
    PRIMARY KEY (UID),
    FOREIGN KEY (WF_UID) REFERENCES G_WF_WORKFLOW(UID)
);

CREATE TABLE G_WF_FIELD (
	UID INTEGER AUTO_INCREMENT NOT NULL,
    WF_UID INTEGER NOT NULL,
    FIELD_LABEL VARCHAR(100) NOT NULL,
    FIELD_TYPE VARCHAR(100) NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    FIELD_SEQ INTEGER,
    MANDATORY CHAR(1) DEFAULT 'N',
    CREATED_BY VARCHAR(100),
    CREATED_DATE DATETIME,
    UPDATED_BY VARCHAR(100),
    UPDATED_DATE DATETIME,
    DELETE_FLAG CHAR(1) DEFAULT 'N',
    PRIMARY KEY (UID),
    FOREIGN KEY (WF_UID) REFERENCES G_WF_WORKFLOW(UID)
);

CREATE TABLE G_WF_FIELD_OPTION (
	UID INTEGER AUTO_INCREMENT NOT NULL,
    FIELD_UID INTEGER NOT NULL,
    LABEL VARCHAR(100) NOT NULL,
    FIELD_VALUE VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_DATE DATETIME,
    UPDATED_BY VARCHAR(100),
    UPDATED_DATE DATETIME,
    DELETE_FLAG CHAR(1) DEFAULT 'N',
    PRIMARY KEY (UID),
    FOREIGN KEY (FIELD_UID) REFERENCES G_WF_FIELD(UID)
);